// THIS FILE IS AUTO-GENERATED BY THE SUPABASE CLI.
// DO NOT EDIT MANUALLY.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      articles: {
        Row: {
          id: string
          title: string
          description: string
          imageUrl: string
          url: string
          vendor_id: string
        }
        Insert: {
          id?: string
          title: string
          description: string
          imageUrl: string
          url: string
          vendor_id: string
        }
        Update: {
          id?: string
          title?: string
          description?: string
          imageUrl?: string
          url?: string
          vendor_id?: string
        }
      }
      comments: {
        Row: {
          id: string
          user_id: string
          text: string
          timestamp: string
          likes: number
          parent_comment_id: string | null
          video_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      contact_persons: {
        Row: {
          id: string
          name: string
          title: string
          email: string
          avatarUrl: string
          vendor_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      documentation_items: {
        Row: {
          id: string
          title: string
          type: "Cut Sheet" | "Specification" | "Drawing" | "Collateral" | "Guide" | "Checklist" | "Comparison"
          category: string
          downloads: number
          updatedAt: string
          tags: string[]
          annualSavings: number
          previewImageUrl: string
          documentUrl: string
          isFeatured: boolean
          performanceMetrics: Json | null
          complianceStatus: string | null
          roi: number | null
          vendor_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      droobi_videos: {
        Row: {
          id: string
          title: string
          description: string
          thumbnailUrl: string
          videoUrl: string
          category: string
          durationMinutes: number
          airDate: string
          source: "AI News" | "Partner" | null
          series_info: Json | null // For series title and episode
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      impact_metrics: {
        Row: {
          id: string
          name: string
          value: string
          description: string
          term_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      lexicon_terms: {
        Row: {
          id: string
          term: string
          category: string
          plainLanguageDefinition: string
          technicalDefinition: string
          regulatoryReferences: string[]
          designAndOMNotes: string
          risksAndFailureModes: string[]
          useCases: string[]
          impactMetrics: Json // Will hold ImpactMetric[]
          resilienceMapping: Json // Will hold ResilienceMapping object
          isPremium: boolean
          caseStudiesCount: number
          demoVideoUrl: string | null
          handbookUrl: string | null
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      on_demand_sessions: {
        Row: {
            id: string;
            title: string;
            author: string;
            views: number;
            rating: number;
            durationMinutes: number;
            watchUrl: string;
            downloadUrl: string;
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      performance_metrics: {
          Row: {
              name: string;
              value: number;
          }
          Insert: { /* ... */ }
          Update: { /* ... */ }
      }
      playlists: {
        Row: {
          id: string
          name: string
          user_id: string
          videoIds: string[]
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      sessions: {
        Row: {
            id: string;
            title: string;
            speaker_id: string;
            dateTime: string;
            durationMinutes: number;
            registeredAttendees: number;
            attendees: number | null;
            description: string;
            category: string;
            tags: string[];
            isLive: boolean;
            isPremium: boolean;
            joinUrl: string;
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      speakers: {
        Row: {
            id: string;
            name: string;
            affiliation: string;
            avatarInitials: string;
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      users: {
        Row: {
          id: string
          name: string
          avatarUrl: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      vendors: {
        Row: {
          id: string
          name: string
          logoUrl: string
          description: string
          email: string
          phone: string
          website: string | null
          isClaimed: boolean
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      videos: {
        Row: {
          id: string
          title: string
          thumbnailUrl: string
          videoUrl: string
          vendor_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
      webinars: {
        Row: {
          id: string
          title: string
          description: string
          dateTime: string
          url: string
          isLive: boolean
          vendor_id: string
        }
        Insert: { /* ... */ }
        Update: { /* ... */ }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
